# Generated by Django 5.1.1 on 2025-01-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default_profile.jpg",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
