# Generated by Django 5.1.1 on 2025-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[(1, "Type 1"), (2, "Type 2")], default=1
            ),
        ),
    ]
