# Generated by Django 5.1.1 on 2025-01-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="notification_type",
            new_name="type",
        ),
    ]
