# Generated by Django 5.1.1 on 2024-12-17 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_conversation_id_remove_message_sender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interest",
            constraint=models.UniqueConstraint(
                fields=("sender", "receiver"), name="unique_interest_per_pair"
            ),
        ),
    ]
