# Generated by Django 5.1.1 on 2025-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_interest_unique_interest_per_pair"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("blocked", "Blocked"),
                ],
                max_length=20,
            ),
        ),
    ]
